all_corner_pairs = [
    'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AK', 'AL', 'AN', 'AO', 'AP', 'AR', 'AS', 'AT', 'AV',
    'AW', 'AZ', 'BA', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BK', 'BL', 'BJ', 'BO', 'BP', 'BM', 'BS',
    'BT', 'BV', 'BW', 'BZ', 'CA', 'CB', 'CD', 'CE', 'CF', 'CH', 'CJ', 'CK', 'CM', 'CN', 'CO', 'CP',
    'CR', 'CS', 'CT', 'CV', 'CW', 'CZ', 'DA', 'DB', 'DC', 'DG', 'DH', 'DJ', 'DK', 'DL', 'DM', 'DN',
    'DO', 'DP', 'DR', 'DS', 'DT', 'DV', 'DW', 'DZ', 'EA', 'EB', 'EC', 'EG', 'EH', 'EJ', 'EK', 'EL',
    'EM', 'EN', 'EO', 'EP', 'ER', 'ES', 'ET', 'EV', 'EW', 'EZ', 'FA', 'FB', 'FC', 'FG', 'FH', 'FJ',
    'FK', 'FL', 'FM', 'FN', 'FO', 'FP', 'FR', 'FS', 'FT', 'FV', 'FW', 'FZ', 'GA', 'GB', 'GD', 'GE',
    'GF', 'GH', 'GJ', 'GK', 'GM', 'GN', 'GO', 'GP', 'GR', 'GS', 'GT', 'GV', 'GW', 'GZ', 'HA', 'HB',
    'HC', 'HD', 'HE', 'HF', 'HG', 'HJ', 'HK', 'HL', 'HM', 'HN', 'HO', 'HP', 'HR', 'HT', 'HV', 'HW',
    'JB', 'JC', 'JD', 'JE', 'JF', 'JG', 'JH', 'JK', 'JL', 'JN', 'JO', 'JP', 'JR', 'JS', 'JT', 'JV',
    'JW', 'JZ', 'KA', 'KB', 'KC', 'KD', 'KE', 'KF', 'KG', 'KH', 'KJ', 'KL', 'KM', 'KN', 'KO', 'KR',
    'KS', 'KT', 'KW', 'KZ', 'LA', 'LB', 'LD', 'LE', 'LF', 'LH', 'LJ', 'LK', 'LM', 'LN', 'LO', 'LP',
    'LR', 'LS', 'LT', 'LV', 'LW', 'LZ', 'MB', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MN',
    'MO', 'MP', 'MR', 'MS', 'MT', 'MV', 'MW', 'MZ', 'NA', 'NC', 'ND', 'NE', 'NF', 'NG', 'NH', 'NJ',
    'NK', 'NL', 'NM', 'NO', 'NP', 'NS', 'NT', 'NV', 'NW', 'NZ', 'OA', 'OB', 'OC', 'OD', 'OE', 'OF',
    'OG', 'OH', 'OJ', 'OK', 'OL', 'OM', 'ON', 'OP', 'OR', 'OS', 'OV', 'OZ', 'PA', 'PB', 'PC', 'PD',
    'PE', 'PF', 'PG', 'PH', 'PJ', 'PL', 'PM', 'PN', 'PO', 'PR', 'PS', 'PT', 'PW', 'PZ', 'RA', 'RC',
    'RD', 'RE', 'RF', 'RG', 'RH', 'RJ', 'RK', 'RL', 'RM', 'RO', 'RP', 'RS', 'RT', 'RV', 'RW', 'RZ',
    'SA', 'SB', 'SC', 'SD', 'SE', 'SF', 'SG', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SP', 'SR', 'ST',
    'SV', 'SW', 'TA', 'TB', 'TC', 'TD', 'TE', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TP',
    'TR', 'TS', 'TV', 'TZ', 'VA', 'VB', 'VC', 'VD', 'VE', 'VF', 'VG', 'VH', 'VJ', 'VL', 'VM', 'VN',
    'VO', 'VR', 'VS', 'VT', 'VW', 'VZ', 'WA', 'WB', 'WC', 'WD', 'WE', 'WF', 'WG', 'WH', 'WJ', 'WK',
    'WL', 'WM', 'WN', 'WP', 'WR', 'WS', 'WV', 'WZ', 'ZA', 'ZB', 'ZC', 'ZD', 'ZE', 'ZF', 'ZG', 'ZJ',
    'ZK', 'ZL', 'ZM', 'ZN', 'ZO', 'ZP', 'ZR', 'ZT', 'ZV', 'ZW',
]
