all_corner_pairs = [
    'AB', 'AC', 'AD', 'AE', 'AF', 'AG', 'AH', 'AK', 'AL', 'AN', 'AO', 'AP', 'AR', 'AS', 'AT', 'AV',
    'AW', 'AZ', 'BA', 'BC', 'BD', 'BE', 'BF', 'BG', 'BH', 'BK', 'BL', 'BJ', 'BO', 'BP', 'BM', 'BS',
    'BT', 'BV', 'BW', 'BZ', 'CA', 'CB', 'CD', 'CE', 'CF', 'CH', 'CJ', 'CK', 'CM', 'CN', 'CO', 'CP',
    'CR', 'CS', 'CT', 'CV', 'CW', 'CZ', 'DA', 'DB', 'DC', 'DG', 'DH', 'DJ', 'DK', 'DL', 'DM', 'DN',
    'DO', 'DP', 'DR', 'DS', 'DT', 'DV', 'DW', 'DZ', 'EA', 'EB', 'EC', 'EG', 'EH', 'EJ', 'EK', 'EL',
    'EM', 'EN', 'EO', 'EP', 'ER', 'ES', 'ET', 'EV', 'EW', 'EZ', 'FA', 'FB', 'FC', 'FG', 'FH', 'FJ',
    'FK', 'FL', 'FM', 'FN', 'FO', 'FP', 'FR', 'FS', 'FT', 'FV', 'FW', 'FZ', 'GA', 'GB', 'GD', 'GE',
    'GF', 'GH', 'GJ', 'GK', 'GM', 'GN', 'GO', 'GP', 'GR', 'GS', 'GT', 'GV', 'GW', 'GZ', 'HA', 'HB',
    'HC', 'HD', 'HE', 'HF', 'HG', 'HJ', 'HK', 'HL', 'HM', 'HN', 'HO', 'HP', 'HR', 'HT', 'HV', 'HW',
    'JB', 'JC', 'JD', 'JE', 'JF', 'JG', 'JH', 'JK', 'JL', 'JN', 'JO', 'JP', 'JR', 'JS', 'JT', 'JV',
    'JW', 'JZ', 'KA', 'KB', 'KC', 'KD', 'KE', 'KF', 'KG', 'KH', 'KJ', 'KL', 'KM', 'KN', 'KO', 'KR',
    'KS', 'KT', 'KW', 'KZ', 'LA', 'LB', 'LD', 'LE', 'LF', 'LH', 'LJ', 'LK', 'LM', 'LN', 'LO', 'LP',
    'LR', 'LS', 'LT', 'LV', 'LW', 'LZ', 'MB', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MN',
    'MO', 'MP', 'MR', 'MS', 'MT', 'MV', 'MW', 'MZ', 'NA', 'NC', 'ND', 'NE', 'NF', 'NG', 'NH', 'NJ',
    'NK', 'NL', 'NM', 'NO', 'NP', 'NS', 'NT', 'NV', 'NW', 'NZ', 'OA', 'OB', 'OC', 'OD', 'OE', 'OF',
    'OG', 'OH', 'OJ', 'OK', 'OL', 'OM', 'ON', 'OP', 'OR', 'OS', 'OV', 'OZ', 'PA', 'PB', 'PC', 'PD',
    'PE', 'PF', 'PG', 'PH', 'PJ', 'PL', 'PM', 'PN', 'PO', 'PR', 'PS', 'PT', 'PW', 'PZ', 'RA', 'RC',
    'RD', 'RE', 'RF', 'RG', 'RH', 'RJ', 'RK', 'RL', 'RM', 'RO', 'RP', 'RS', 'RT', 'RV', 'RW', 'RZ',
    'SA', 'SB', 'SC', 'SD', 'SE', 'SF', 'SG', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SP', 'SR', 'ST',
    'SV', 'SW', 'TA', 'TB', 'TC', 'TD', 'TE', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TP',
    'TR', 'TS', 'TV', 'TZ', 'VA', 'VB', 'VC', 'VD', 'VE', 'VF', 'VG', 'VH', 'VJ', 'VL', 'VM', 'VN',
    'VO', 'VR', 'VS', 'VT', 'VW', 'VZ', 'WA', 'WB', 'WC', 'WD', 'WE', 'WF', 'WG', 'WH', 'WJ', 'WK',
    'WL', 'WM', 'WN', 'WP', 'WR', 'WS', 'WV', 'WZ', 'ZA', 'ZB', 'ZC', 'ZD', 'ZE', 'ZF', 'ZG', 'ZJ',
    'ZK', 'ZL', 'ZM', 'ZN', 'ZO', 'ZP', 'ZR', 'ZT', 'ZV', 'ZW',
]

a = ['L2', 'B2', 'DLDB', 'FDBR', 'RFFL', 'LUBL', 'RUDR', 'U',
     'R2', 'L2', 'U2', 'FRDR', 'RUBD', 'LFLU', 'LDDF', 'RBLB',
     'RUDL', 'DFUL', 'RBRD', 'BLFL', 'DBRF', 'l', "U'", 'R',
     'R2', 'B2', 'RBRU', 'BDDF', 'LULF', 'FRDL', 'RDLB', "S'",
     'U', 'D2', 'LDRB', 'ULDF', 'FRBD', 'RDFL', 'LBUR', 'S',
     'R2', 'L2', 'F2', 'LDUL', 'URFR', 'LFDF', 'BLDR', 'RBBD',
     'B2', 'U2', 'BDUR', 'FRFL', 'LBRD', 'RBFD', 'LDLU', 'R',
     'L2', 'D', 'B2', 'FDDL', 'DRFR', 'BDRB', 'FLUR', 'ULBL',
     'R2', 'U2', 'DFLB', 'RDRF', 'FLLD', 'RBLU', 'RUDB', 'M',
     "D'", 'R2', 'BLUL', 'LFDL', 'BRBD', 'FDRU', 'RDFR', "E'",
     'R2', 'D', 'F2', 'RDBR', 'ULFR', 'DFLF', 'BLDL', 'URBD',
     'B2', 'RDRU', 'RBFR', 'LBDB', 'DLDF', 'LFUL', 'r', 'D',
     'B2', 'D', 'RBDL', 'LFDR', 'DBFD', 'LBUL', 'FRUR', "U'",
     'D', 'R2', "D'", 'BDRU', 'RBUL', 'DFDR', 'FRLD', 'LFBL',
     'L2', "U'", 'LDFR', 'DBRB', 'RDUR', 'ULLF', 'LBFD', "L'",
     'L2', 'D', 'URRD', 'DLLF', 'BRLB', 'FDDB', 'FRUL', 'U',
     "U'", 'B2', 'ULDR', 'URBL', 'BRFD', 'BDFR', 'LDLF', "U'",
     'U', 'L2', 'D', 'BLDF', 'DBFR', 'RDLU', 'URDL', 'BRFL',
     'L2', 'D', 'RUDF', 'LDDR', 'FLBD', 'ULLB', 'FRRB', 'r',
     "U'", 'F2', 'B2', 'FDRB', 'LBBD', 'ULRU', 'DRFL', 'RFLD',
     'U', 'D', 'FRDF', 'DLRD', 'BRDB', 'RUFL', 'LULB', 'M2',
     'R2', 'F2', 'B2', 'DFLD', 'DRBL', 'BDLF', 'RFUR', 'LURB',
     'D', 'B2', 'LFUR', 'BLFD', 'DLBD', 'DRRB', 'RFLU', "R'",
     "D'", 'R2', 'FLDR', 'LUDF', 'DBUR', 'LDBL', 'BRFR', 'U',
     "D'", 'L2', 'B2', 'RULB', 'DBDF', 'RFUL', 'LDFL', 'RBDR',
     'F2', 'B2', 'FLUL', 'RFLB', 'DBDL', 'DFRD', 'RUBR', 'E',
     'B2', 'L2', 'D2', 'LBLF', 'FDRD', 'RBLD', 'URUL', 'FRDB',
     'B2', 'D', 'RFBD', 'LBDL', 'LFFD', 'BRRU', 'DRUL', 'M2',
     'R2', 'F2', 'DRLD', 'ULFD', 'BDRF', 'URLB', 'FLBR', 'S',
     'U2', 'LUBR', 'FLRD', 'FDFR', 'BLUR', 'LDBD', 'M', 'U',
     'R2', 'B2', 'BDBL', 'ULBR', 'FDRF', 'RULF', 'DRDL', "U'",
     "U'", 'B2', 'R2', 'RDFD', 'FRLU', 'BDLB', 'LFRU', 'BRLD',
     'B2', 'D', 'LDUR', 'LFFR', 'DRLB', 'RBDB', 'DFLU', "U2'",
     'L2', 'B2', 'BDRD', 'BLBR', 'URRF', 'DLFL', 'FDLU', 'r',
     'B2', "U'", 'L2', 'DLDR', 'RUBL', 'DBFL', 'ULRF', 'BRDF',
     'B2', 'L2', 'ULDB', 'RBBL', 'DRFD', 'RFDL', 'URLF', "M'",
     'B2', 'D2', 'LUDL', 'RDDB', 'BRRF', 'URDF', 'LFLB', "L'",
     "D'", 'R2', 'U', 'BRDL', 'LUFL', 'URDB', 'DRRF', 'DFBL',
     'F2', 'R2', 'U', 'LDRU', 'FLDB', 'LURF', 'DRDF', 'BLRB',
     'L2', 'U2', 'BRDR', 'URFD', 'ULDL', 'BLBD', 'FLRF', 'R2',
     "U'", 'R2', 'BLLU', 'DBBR', 'LFRF', 'LDFD', 'DRRU', "r'",
     'LBRB', 'RDUL', 'DFUR', 'FLFR', 'DBLD', 'U', 'E', 'L',
     'D2', 'R2', 'RDDL', 'FLRU', 'BDFD', 'FRBR', 'LBLU', "R'",
     'F2', 'B2', 'ULRB', 'FDFL', 'DBLB', 'RFDR', 'DLUR', "U'",
     'D', 'FRLF', 'RURB', 'DRDB', 'DLBL', 'LUFD', 'R', 'U',
     'R2', 'B2', 'DLLB', 'RBLF', 'LUUR', 'RDBD', 'FRFD', "U'",
     "U'", 'F2', 'L2', '.', 'BRUR', 'DBRD', 'FLDF', 'FRLB',
     'L2', 'B2', 'D', 'LFRD', 'DLRF', 'FDUL', 'BLDB', 'URRB',
     'LURU', 'LDLB', 'LFRB', 'RFFD', 'BDDR', "M'", "U'", 'M', ]
a = {i for i in a if len(i) == 4}
print(a)
